"""
Agent response models.

Design:
    SubQueryResult captures the outcome of a single sub-query execution,
    including answer text, confidence, sources, and failure metadata.
    AgentResponse aggregates all sub-results with synthesis output and
    exposes to_rag_response() for callers that don't need agent internals.

Chain of Responsibility:
    ParallelRetriever produces List[SubQueryResult] → ResultVerifier updates
    them → AnswerSynthesizer reads them → AgentOrchestrator assembles
    AgentResponse → RAGPipeline calls to_rag_response().

Dependencies:
    pydantic, rag.models.rag_response
"""

# stdlib
from typing import Optional

# third-party
from pydantic import BaseModel, ConfigDict, Field

# internal
from rag.models.rag_response import (
    ConfidenceScore,
    RAGResponse,
    RAGTimings,
    RetrievedChunk,
)


class SubQueryResult(BaseModel):
    """Result of a single sub-query execution.

    Attributes:
        sub_query_id: ID of the sub-query that produced this result.
        query: The sub-query text that was executed.
        collection: Collection that was queried.
        purpose: What this sub-query was meant to resolve (from the planner).
        answer: The answer from the RAG pipeline, or empty on failure.
        confidence: Confidence score from the RAG response.
        sources: Retrieved chunks used in the answer.
        success: Whether the sub-query produced a usable answer.
        failure_reason: Why the sub-query failed, if applicable.
        latency_ms: Execution time for this sub-query.
        prompt_tokens: Input tokens consumed by the sub-query LLM call.
        completion_tokens: Output tokens generated by the sub-query LLM call.
    """

    model_config = ConfigDict(frozen=True)

    sub_query_id: str
    query: str
    collection: str
    purpose: str = ""
    answer: str = ""
    confidence: float = Field(default=0.0, ge=0.0, le=1.0)
    sources: list[RetrievedChunk] = Field(default_factory=list)
    success: bool = True
    failure_reason: str = ""
    latency_ms: float = Field(default=0.0, ge=0.0)
    prompt_tokens: int = Field(default=0, ge=0)
    completion_tokens: int = Field(default=0, ge=0)

    @classmethod
    def from_rag_response(
        cls,
        sub_query_id: str,
        query: str,
        collection: str,
        response: RAGResponse,
        latency_ms: float,
        purpose: str = "",
    ) -> "SubQueryResult":
        """Create from a successful RAG pipeline response.

        Args:
            sub_query_id: ID of the originating sub-query.
            query: The sub-query text.
            collection: Collection that was queried.
            response: RAGResponse from the pipeline.
            latency_ms: Execution time in milliseconds.
            purpose: What this sub-query was meant to resolve.

        Returns:
            SubQueryResult marked as successful.
        """
        return cls(
            sub_query_id=sub_query_id,
            query=query,
            collection=collection,
            purpose=purpose,
            answer=response.answer,
            confidence=response.confidence.value if response.confidence else 0.0,
            sources=response.sources or [],
            success=True,
            latency_ms=latency_ms,
            prompt_tokens=response.prompt_tokens,
            completion_tokens=response.completion_tokens,
        )

    @classmethod
    def from_failure(
        cls,
        sub_query_id: str,
        query: str,
        collection: str,
        reason: str,
        latency_ms: float,
        purpose: str = "",
    ) -> "SubQueryResult":
        """Create from a failed sub-query execution.

        Args:
            sub_query_id: ID of the originating sub-query.
            query: The sub-query text.
            collection: Collection that was queried.
            reason: Human-readable failure description.
            latency_ms: Time spent before failure.
            purpose: What this sub-query was meant to resolve.

        Returns:
            SubQueryResult marked as failed.
        """
        return cls(
            sub_query_id=sub_query_id,
            query=query,
            collection=collection,
            purpose=purpose,
            success=False,
            failure_reason=reason,
            latency_ms=latency_ms,
        )


class AgentResponse(BaseModel):
    """Full agent response with sub-query transparency.

    Wraps the synthesized answer with metadata about the decomposition,
    individual sub-query results, and aggregate metrics.

    Attributes:
        answer: The final synthesized answer.
        sub_results: Results from each sub-query.
        plan_reasoning: The planner's decomposition reasoning.
        confidence: Aggregate confidence across sub-queries.
        total_sub_queries: Number of sub-queries planned.
        successful_sub_queries: Number that succeeded.
        failed_sub_queries: Number that failed.
        timings: Aggregate timing breakdown.
        request_id: Parent request ID for tracing.
        model_name: LLM model used for synthesis.
        prompt_tokens: Total prompt tokens across all calls.
        completion_tokens: Total completion tokens across all calls.
    """

    model_config = ConfigDict(frozen=True)

    answer: str
    sub_results: list[SubQueryResult] = Field(default_factory=list)
    plan_reasoning: str = ""
    confidence: ConfidenceScore = Field(
        default_factory=lambda: ConfidenceScore(value=0.0, method="agent"),
    )
    total_sub_queries: int = Field(default=0, ge=0)
    successful_sub_queries: int = Field(default=0, ge=0)
    failed_sub_queries: int = Field(default=0, ge=0)
    timings: RAGTimings = Field(
        default_factory=lambda: RAGTimings(
            retrieval_ms=0.0, ranking_ms=0.0,
            generation_ms=0.0, total_ms=0.0,
        ),
    )
    request_id: str = ""
    model_name: str = ""
    prompt_tokens: int = Field(default=0, ge=0)
    completion_tokens: int = Field(default=0, ge=0)

    def to_rag_response(self) -> RAGResponse:
        """Collapse to a standard RAGResponse.

        Useful for callers that don't care about agent internals —
        the pipeline and backend can return a uniform type.

        Returns:
            RAGResponse with the synthesized answer and aggregate metadata.
        """
        # Collect sources only from successful sub-queries.
        all_sources = []
        for sr in self.sub_results:
            if sr.success:
                all_sources.extend(sr.sources)

        return RAGResponse(
            answer=self.answer,
            sources=all_sources,
            timings=self.timings,
            confidence=self.confidence,
            cache_hit=False,
            cache_layer=None,
            rag_variant="agent",
            context_tokens_used=0,
            model_name=self.model_name,
            request_id=self.request_id,
            prompt_tokens=self.prompt_tokens,
            completion_tokens=self.completion_tokens,
        )
